DROP DATABASE if EXISTS emptracker_db;

CREATE DATABASE emptracker_db;

USE emptracker_db;

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name_ VARCHAR(30) NOT NULL);

CREATE TABLE role (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
salary DECIMAL NOT NULL,
department_id INT NOT NULL);

CREATE TABLE employee (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT NOT NULL,
manager_id INT NOT NULL); 